version: "3.7"

services:
  backend:
    container_name: me-fdsz-backend
    image: vmarci94/me-fdsz-be:latest
    restart: always
    ports:
      - 8081:8081
      - 33061:3306
    depends_on:
      - db
    links:
      - "db:database"
  db:
    container_name: me-fdsz-database
    image: mysql
    environment:
      MYSQL_USER: marci
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ME_FDSZ
    restart: always
  frontend:
    container_name: me-fdsz-frontend
    image: vmarci94/me-fdsz-fe:latest
    restart: always
    depends_on:
      - backend
    links:
      - "backend:backend"
    ports:
      - 4201:80





